Feature: search book view
digital-gachilib/meadow pull request #2
Opened 2020-04-04 21:11 UTC by Alwa0

2020-04-05 08:54 UTC, Birdi7 requested changes

2020-04-05 08:54 UTC, Birdi7 commented on meadow/book_searcher.py
> +from polls.models import Book
давай перенесем файл book_searcher.py в meadow/utils/book_searcher.py. в корне проекта надо по минимуму добавлять что-то, кроме `manage.py`. основная папка, в которой работаем, это meadow/meadow

2020-04-05 08:54 UTC, Birdi7 commented on meadow/meadow/settings.py
> +    "polls.apps.PollsConfig",
давай уберем приложение `polls` из проекта. пока только `meadow` приложение будет, и твоя ручка в нем должна быть

2020-04-05 08:54 UTC, Birdi7 commented on meadow/polls/urls.py
> +    path("", views.search, name="search"),
вот это нужно будет перенести в meadow/urls.py
и назови как-нибудь путь к вьюшке(первый аргумент). book_search, например

2020-04-05 08:54 UTC, Birdi7 commented on meadow/urls.py
> +]
не понял, зачем этот файл нужен, почему ты решила его добавить?

2020-04-05 08:54 UTC, Birdi7 commented on meadow/polls/views.py
> +    search_by_title("")
а разве вернуть не нужно книги из вюхи?

2020-04-05 08:54 UTC, Birdi7 commented on meadow/polls/models.py
> +from django.db import models
это тоже переносится в meadow/models.py, соответственно

2020-04-05 08:54 UTC, Birdi7 commented on meadow/polls/migrations/0001_initial.py
> +# Generated by Django 3.1 on 2020-04-02 12:22
миграции не переноси вручную ток, после перемещения вюхи в `meadow` перегенерируй просто, а эти удали

2020-04-05 08:54 UTC, Birdi7 commented on meadow/polls/admin.py
> +from django.contrib import admin
тоже в meadow/admin

2020-04-05 08:54 UTC, Birdi7 commented on meadow/meadow/urls.py
> +    path("polls/", include("polls.urls")),
тут вместо ручки на polls как раз будет ручка на book searcher

2020-04-06 07:23 UTC, Alwa0 commented on meadow/polls/models.py
> +from django.db import models
я не поняла что вот тут ты имеешь ввиду

2020-04-06 07:26 UTC, Alwa0 commented on meadow/polls/migrations/0001_initial.py
> +# Generated by Django 3.1 on 2020-04-02 12:22
я вручную не переносила вроде, этот файлик сам создался

2020-04-06 15:50 UTC, Birdi7 commented
пример запроса using httpie:
`http "localhost:8000/book_searcher/title 1"`

2020-04-06 17:42 UTC, Birdi7 approved these changes

2020-04-06 17:59 UTC, merged