Login logic and requirements.txt update
digital-gachilib/meadow pull request #3
Opened 2020-04-04 21:59 UTC by JottoWorol

add djungorestframework to requirements.txt
created view for login
created authorization token with login:bossofthegym pass:dungeonmaster

2020-04-04 22:02 UTC, Birdi7 commented on requirements.txt
> +pkg-resources==0.0.0
какой-то баг в убунте, надо бы убрать 
https://stackoverflow.com/questions/39577984/what-is-pkg-resources-0-0-0-in-output-of-pip-freeze-command
```suggestion
```

2020-04-05 08:36 UTC, Birdi7 commented on meadow/meadow/urls.py
> +    path("hello/", views.HelloView.as_view(), name="hello"),
@KamilRizatdinov ты как думаешь, убрать HelloView, или стоит оставить пока, для тестов на фронте?

2020-04-05 08:37 UTC, Birdi7 commented
все ок, только нужно убрать из requirements.txt лишнее

2020-04-05 08:59 UTC, Birdi7 requested changes
все ок, только нужно убрать из requirements.txt лишнее

2020-04-05 09:25 UTC, KamilRizatdinov commented on meadow/meadow/urls.py
> +    path("hello/", views.HelloView.as_view(), name="hello"),
Он для тестов фронта не нужен особо, можно убрать.
Главное чтобы ручка  **../api-token-auth/** работала как нужно. 
@Birdi7

2020-04-05 10:47 UTC, Birdi7 commented on meadow/meadow/urls.py
> +    path("hello/", views.HelloView.as_view(), name="hello"),
@JottoWorol, тогда давай уберем эту вьюху

2020-04-06 08:41 UTC, Birdi7 approved these changes

2020-04-06 09:04 UTC, merged